max_messages_per_day: 300
min_delay: 5
max_delay: 10

message_text: "ä½ å¥½ï¼Œæ¬¢è¿è®¢é˜…ä¸œå—äºšå¤§äº‹ä»¶ã€Œæ›å…‰ã€ï¼Œé“¾æ¥: https://t.me/bigeventsinsea æœ€å…¨çš„æ›å…‰å†…å®¹ï¼ ğŸ˜Š"

channels:
  - link: https://t.me/dny185
  - link: https://t.me/dashijian9
  - link: https://t.me/feilvbindsj0
  - link: https://t.me/SJTFLP
  - link: https://t.me/feilvbingi
  - link: https://t.me/jinbiany
  - link: https://t.me/miandianDS
  - link: https://t.me/SJTJPZ
  - link: https://t.me/zh_cnjjii
  - link: https://t.me/MB98888
  - link: https://t.me/miandiandashijian168
  - link: https://t.me/miandiande
  - link: https://t.me/sucain7
  - link: https://t.me/kk90690
  - link: https://t.me/bx1OO
  - link: https://t.me/TQxinwen
  - link: https://t.me/tqbgq
  - link: https://t.me/kkyuanqudajian
  - link: https://t.me/xigang818
  - link: https://t.me/dubai0
  - link: https://t.me/pyzcn
  - link: https://t.me/haiwaidjs
  - link: https://t.me/hwdsj2
  - link: https://t.me/zh_cnyes1
  - link: https://t.me/dnyggg
  - link: https://t.me/cn_zhm0
  - link: https://t.me/dongnanya01
  - link: https://t.me/eeollse
  - link: https://t.me/jpz_888
  - link: https://t.me/xgsj9
  - link: https://t.me/tx100
  - link: https://t.me/pueee
  - link: https://t.me/dj17baoguang
  - link: https://t.me/Spri1te3mr
  - link: https://t.me/hadsj_JLQ
  - link: https://t.me/zh_cnshk
  - link: https://t.me/YTCSJ6
  - link: https://t.me/dongnanya127
  - link: https://t.me/flbadrj
  - link: https://t.me/PG134

accounts:
  - session: user1 # +85264887781
    api_id: 28061491
    api_hash: 4f8831b3cb5a07f601f28f8295f934d4

  - session: user2 # +85264854380
    api_id: 24382238
    api_hash: a926790195b42a472477e7709a74fc24
