max_messages_per_day: 300
min_delay: 5
max_delay: 10

message_text: "ä½ å¥½ï¼Œæ¬¢è¿è®¢é˜…ä¸œå—äºšå¤§äº‹ä»¶ã€Œæ›å…‰ã€ï¼Œé“¾æ¥: https://t.me/bigeventsinsea æœ€å…¨çš„æ›å…‰å†…å®¹ï¼ ğŸ˜Š"

channels:
  - link: https://t.me/bigeventsinsea

accounts:
  - session: user1 # +85264887781
    api_id: 28061491
    api_hash: 4f8831b3cb5a07f601f28f8295f934d4

  - session: user2 # +85264854380
    api_id: 24382238
    api_hash: a926790195b42a472477e7709a74fc24
